Repository codestates-seb/seb45_main_002, pull requests merged in 2023-09, with the labels that each got.

#53 login, signup 모달
  Client/prettierrc.json
  Client/src/App.js
  Client/src/atom/GlobalModal.jsx
  Client/src/component/Header.js
  Client/src/component/Login.js
  Client/src/component/LoginForm.jsx
  Client/src/component/Main.js
  Client/src/component/Nav.js
  Client/src/component/SignUp.js
  Client/src/component/SignUpForm.jsx
  Client/src/page/Home.js
  Client/src/page/MyPage.js
  Client/src/style/style.js
Labels: FE

#49 Feat #17 커뮤니티 게시글 수정 기능 추가
  main_project/src/main/java/NutrientsCoders/main_project/MainProjectApplication.java
  main_project/src/main/java/NutrientsCoders/main_project/community/controller/CommunityController.java
  main_project/src/main/java/NutrientsCoders/main_project/community/dto/CommunityMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/community/dto/CommunityPatchDto.java
  main_project/src/main/java/NutrientsCoders/main_project/community/dto/CommunityPostDto.java
  main_project/src/main/java/NutrientsCoders/main_project/community/dto/CommunityResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/community/entity/Community.java
  main_project/src/main/java/NutrientsCoders/main_project/community/entity/CommunityBaseTime.java
  main_project/src/main/java/NutrientsCoders/main_project/community/repository/CommunityRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/community/service/CommunityService.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/dto/MultiResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/dto/PageInfo.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/ExceptionCode.java
Labels: BE, CodeReview

#50 Member관련 CRUD+email중복체크+bmi&kcal계산
  main_project/src/main/java/NutrientsCoders/main_project/member/controller/MemberController.java
  main_project/src/main/java/NutrientsCoders/main_project/member/dto/MemberDto.java
  main_project/src/main/java/NutrientsCoders/main_project/member/dto/MemberMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/member/dto/MemberResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/member/entity/Member.java
  main_project/src/main/java/NutrientsCoders/main_project/member/repository/MemberRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/member/service/MemberService.java
  main_project/src/main/java/NutrientsCoders/main_project/member/service/MemberServiceImpl.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/UriCreator.java
Labels: BE, CodeReview

#58 restart
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealPatchDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealPostDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/entity/DailyMeal.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/mapper/DailyMealMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/repository/DailyMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/controller/EachMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealFoodDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealFoodResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealPatchDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealPostDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMeal.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMealFood.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/mapper/EachMealMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/repository/EachMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/service/EachMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/food/controller/FoodController.java
  main_project/src/main/java/NutrientsCoders/main_project/food/dto/FoodPatchDto.java
  main_project/src/main/java/NutrientsCoders/main_project/food/dto/FoodPostDto.java
  main_project/src/main/java/NutrientsCoders/main_project/food/dto/FoodResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/food/entity/EtcNutrients.java
  main_project/src/main/java/NutrientsCoders/main_project/food/entity/Food.java
  main_project/src/main/java/NutrientsCoders/main_project/food/mapper/FoodMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/food/repository/EtcNutrientsRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/food/repository/FoodRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/food/service/FoodService.java
Labels: BE, CodeReview

#70 Feat/each meal
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealPatchDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/controller/EachMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealFoodDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealFoodResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealPatchDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealPostDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMeal.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMealFood.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/mapper/EachMealMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/repository/EachMealFoodRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/repository/EachMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/service/EachMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/food/controller/FoodController.java
  main_project/src/main/java/NutrientsCoders/main_project/food/dto/FoodPatchDto.java
  main_project/src/main/java/NutrientsCoders/main_project/food/dto/FoodPostDto.java
  main_project/src/main/java/NutrientsCoders/main_project/food/dto/FoodResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/food/entity/Food.java
  main_project/src/main/java/NutrientsCoders/main_project/food/mapper/FoodMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/food/repository/EtcNutrientsRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/food/repository/FoodRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/food/service/FoodService.java
  main_project/src/main/java/NutrientsCoders/main_project/member/controller/MemberController.java
  main_project/src/main/java/NutrientsCoders/main_project/member/entity/Member.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/ExceptionCode.java
  main_project/src/main/resources/application.yml
Labels: BE, CodeReview

#103 [BE] Access Token을 활용한 값 추출
  main_project/src/main/java/NutrientsCoders/main_project/member/controller/MemberController.java
  main_project/src/main/java/NutrientsCoders/main_project/member/repository/MemberRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/security/SecurityConfig.java
  main_project/src/main/java/NutrientsCoders/main_project/security/jwt/JwtAuthenticationFilter.java
  main_project/src/main/java/NutrientsCoders/main_project/security/jwt/JwtTokenMaker.java
  main_project/src/main/java/NutrientsCoders/main_project/security/jwt/JwtVerificationFilter.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/TokenChanger.java
Labels: BE, CodeReview

#104 [BE] feat Community #43 Community&CommunityComment 연관관계 설정
  main_project/src/main/java/NutrientsCoders/main_project/community/controller/CommunityController.java
  main_project/src/main/java/NutrientsCoders/main_project/community/dto/CommunityAllResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/community/dto/CommunityMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/community/entity/Community.java
  main_project/src/main/java/NutrientsCoders/main_project/community/service/CommunityService.java
  main_project/src/main/java/NutrientsCoders/main_project/communitycomment/dto/CommunityCommentPatchDto.java
  main_project/src/main/java/NutrientsCoders/main_project/communitycomment/dto/CommunityCommentPostDto.java
  main_project/src/main/java/NutrientsCoders/main_project/communitycomment/dto/CommunityCommentResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/communitycomment/entity/CommunityComment.java
  main_project/src/main/java/NutrientsCoders/main_project/communitycomment/repository/CommunityCommentRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/communitycomment/service/CommunityCommentService.java
  main_project/src/main/java/NutrientsCoders/main_project/security/SecurityConfig.java
Labels: BE, CodeReview

#107 Feat/daily meal
  main_project/src/main/java/NutrientsCoders/main_project/community/controller/CommunityController.java
  main_project/src/main/java/NutrientsCoders/main_project/community/service/CommunityService.java
  main_project/src/main/java/NutrientsCoders/main_project/communitycomment/controller/CommunityCommentController.java
  main_project/src/main/java/NutrientsCoders/main_project/communitycomment/service/CommunityCommentService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealDateController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealMultiResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealPostDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/entity/DailyMeal.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/mapper/DailyMealMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/repository/DailyMealDateRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/repository/DailyMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealDateService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/dummy/DummyDataLoader.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/controller/EachMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealResponseSimpleDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMeal.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMealFood.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/mapper/EachMealMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/repository/EachMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/service/EachMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/food/controller/FoodController.java
  main_project/src/main/java/NutrientsCoders/main_project/food/entity/EtcNutrients.java
  main_project/src/main/java/NutrientsCoders/main_project/food/entity/Food.java
  main_project/src/main/java/NutrientsCoders/main_project/food/repository/FoodRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/food/service/FoodService.java
  main_project/src/main/java/NutrientsCoders/main_project/security/jwt/JwtAuthenticationFilter.java
  main_project/src/main/java/NutrientsCoders/main_project/security/jwt/JwtTokenMaker.java
  main_project/src/main/java/NutrientsCoders/main_project/security/jwt/JwtVerificationFilter.java
  main_project/src/main/resources/application.yml
Labels: BE, CodeReview

#115 [BE] SuccessHandler 추가 + bmi,kcal 작동 방식 변경
  main_project/build.gradle
  main_project/src/main/java/NutrientsCoders/main_project/member/controller/MemberController.java
  main_project/src/main/java/NutrientsCoders/main_project/member/dto/MemberResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/member/entity/Member.java
  main_project/src/main/java/NutrientsCoders/main_project/member/service/MemberServiceImpl.java
  main_project/src/main/java/NutrientsCoders/main_project/security/CorsResolver.java
  main_project/src/main/java/NutrientsCoders/main_project/security/SecurityConfig.java
  main_project/src/main/java/NutrientsCoders/main_project/security/SecurityTestController.java
  main_project/src/main/java/NutrientsCoders/main_project/security/custom/LoginSuccessHandler.java
  main_project/src/main/java/NutrientsCoders/main_project/security/jwt/JwtAuthenticationFilter.java
  main_project/src/main/java/NutrientsCoders/main_project/security/jwt/JwtVerificationFilter.java
  main_project/src/main/resources/application.yml
Labels: BE, CodeReview

#117 Feat/analysis
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/controller/AnalysisController.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/dto/AnalysisResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/entity/Analysis.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/mapper/AnalysisMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/repository/AnalysisRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/service/AnalysisService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealDateController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealSimpleResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/mapper/DailyMealMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/controller/EachMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/service/EachMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/ExceptionCode.java
Labels: BE, CodeReview

#118 [BE] OAuth2 -google- 로그인 구현
  main_project/build.gradle
  main_project/src/main/java/NutrientsCoders/main_project/member/entity/Member.java
  main_project/src/main/java/NutrientsCoders/main_project/member/service/MemberService.java
  main_project/src/main/java/NutrientsCoders/main_project/member/service/MemberServiceImpl.java
  main_project/src/main/java/NutrientsCoders/main_project/security/OAuth2/OAuth2SuccessHandler.java
  main_project/src/main/java/NutrientsCoders/main_project/security/SecurityConfig.java
  main_project/src/main/java/NutrientsCoders/main_project/security/SecurityTestController.java
  main_project/src/main/resources/application.yml
Labels: BE, CodeReview

#120 Feat/suggest meal
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/controller/AnalysisController.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/dto/AnalysisResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/entity/Analysis.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/repository/AnalysisRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/service/AnalysisService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealDateController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/entity/DailyMeal.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/mapper/DailyMealMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealSuggestService.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/controller/EachMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMeal.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMealFood.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/service/EachMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/food/entity/Food.java
  main_project/src/main/java/NutrientsCoders/main_project/food/repository/FoodSuggestRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/food/service/FoodService.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/ExceptionCode.java
Labels: BE

#128 Exception handler
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/ExceptionCode.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/GlobalExceptionHandler.java
Labels: BE, CodeReview

#127 [BE] mypage token화
  main_project/src/main/java/NutrientsCoders/main_project/member/controller/MemberController.java
Labels: BE, CodeReview

#143 분석결과 정리, 식단 날짜 검증로직 추가
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/controller/AnalysisController.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/dto/AnalysisResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/entity/Analysis.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/mapper/AnalysisMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/service/AnalysisService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealDateController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/dto/DailyMealSimpleResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/entity/DailyMeal.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/repository/DailyMealDateRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/repository/DailyMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealDateService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealSuggestService.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/controller/EachMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMeal.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/entity/EachMealFood.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/repository/EachMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/service/EachMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/food/dto/FoodPatchDto.java
  main_project/src/main/java/NutrientsCoders/main_project/food/dto/FoodPostDto.java
  main_project/src/main/java/NutrientsCoders/main_project/food/dto/FoodResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/food/entity/EtcNutrients.java
  main_project/src/main/java/NutrientsCoders/main_project/food/entity/Food.java
  main_project/src/main/java/NutrientsCoders/main_project/food/repository/FoodRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/food/repository/FoodSuggestRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/member/entity/Member.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/ExceptionCode.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/GlobalExceptionHandler.java
Labels: BE

#148 [BE] 식단 추천 repository 조회 오류 수정 + 추천 로직 (밸런스)조정
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealSuggestService.java
  main_project/src/main/java/NutrientsCoders/main_project/food/repository/FoodSuggestRepository.java
Labels: BE, CodeReview

#155 Dev fe community
  Client/src/component/Article.jsx
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
  Client/src/page/MyPage.jsx
  Client/src/zustand/ArticleStore.jsx
Labels: FE

#154 Feat/analysis info
  main_project/build.gradle
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/dto/AnalysisResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/entity/Analysis.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/mapper/AnalysisMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/service/AnalysisService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealDateController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealDateService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/controller/EachMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/mapper/EachMealMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/repository/EachMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/service/EachMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/ExceptionCode.java
Labels: BE, CodeReview

#160 paginate
  Client/package-lock.json
  Client/package.json
  Client/src/component/FavoriteDiet.jsx
  Client/src/component/paginate/paginate.jsx
Labels: FE

#159 [BE]구조정리, 기타 오류픽스, 끼니 재사용
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealDateController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/repository/DailyMealDateRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/repository/DailyMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealDateService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealService.java
Labels: BE, CodeReview

#163 [BE]페이지네이션 response Dto추가, analysis 오류로그처리, 식단 수정 오류픽스
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/controller/AnalysisController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealDateController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/controller/EachMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/service/EachMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/food/entity/Food.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/PagedResponse.java
  main_project/src/main/java/NutrientsCoders/main_project/utils/exception/ExceptionCode.java
Labels: BE, CodeReview

#167 pagenation 99% clear
  Client/package-lock.json
  Client/package.json
  Client/src/component/paginate/paginate.jsx
  Client/src/page/Community.jsx
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
  Client/src/zustand/Store.jsx
Labels: FE

#170 Feat/fixed
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealDateController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealSuggestService.java
Labels: BE

#172 clear
  Client/src/component/Article.jsx
  Client/src/component/Comments.jsx
  Client/src/component/LoginForm.jsx
  Client/src/component/SearchForm.jsx
  Client/src/component/SignUpForm.jsx
  Client/src/page/Community.jsx
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
  Client/src/page/MyPage.jsx
  Client/src/zustand/Store.jsx
Labels: FE

#174 [BE]Feat/fixed(식단관련)
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/controller/DailyMealDateController.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/repository/DailyMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealDateService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealSuggestService.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/dto/EachMealDto.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/mapper/EachMealMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/repository/EachMealRepository.java
  main_project/src/main/java/NutrientsCoders/main_project/eachmeal/service/EachMealService.java
Labels: BE

#175 남발하였던 navigate 기능을 Link로 변경, 게시글 수정 등 기능 추가
  Client/src/component/Article.jsx
  Client/src/component/Comments.jsx
  Client/src/page/Community.jsx
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
  Client/src/zustand/Store.jsx
Labels: FE

#176 모든 기능적인 부분 clear, 뽑은 식단데이터 출력을 위해 정리중
  Client/src/component/Article.jsx
  Client/src/component/Comments.jsx
  Client/src/page/Community.jsx
  Client/src/page/CommunityDetail.jsx
Labels: FE

#177 blahblah
  Client/src/component/PageSwitch.jsx
  Client/src/page/Home.jsx
Labels: FE

#178 로그인 이후에 사용할 수 있는 기능들을 비로그인 시, 접근금지
  Client/src/component/Comments.jsx
  Client/src/page/Community.jsx
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
  Client/src/page/MyPage.jsx
Labels: FE

#182 write clear
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
Labels: FE

#183 detail clear
  Client/src/page/CommunityDetail.jsx
Labels: FE

#181 [BE]오타 수정, 탄단지 적정비율 fix, 분석 표시 보완
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/controller/AnalysisController.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/dto/AnalysisResponseDto.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/entity/Analysis.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/mapper/AnalysisMapper.java
  main_project/src/main/java/NutrientsCoders/main_project/Analysis/service/AnalysisService.java
  main_project/src/main/java/NutrientsCoders/main_project/dailymeal/service/DailyMealSuggestService.java
Labels: BE

#190 last
  Client/src/component/FavoriteDiet.jsx
  Client/src/component/Header.jsx
  Client/src/page/Community.jsx
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
  Client/src/page/MyPage.jsx
Labels: FE

#202 don meal write
  Client/src/page/CommunityDetail.jsx
  Client/src/page/MyPage.jsx
Labels: FE

#207 Dev fe community
  Client/src/page/MyPage.jsx
Labels: FE

#208 Dev fe
  Client/src/App.jsx
  Client/src/asset/hamburgerIcon.png
  Client/src/asset/navCommunityIcon.png
  Client/src/asset/navHomeIcon.png
  Client/src/asset/navMyPageIcon.png
  Client/src/asset/searchIcon.svg
  Client/src/atom/Hamberger.jsx
  Client/src/component/Calendar.jsx
  Client/src/component/Calendar/Calendar.jsx
  Client/src/component/Calendar/CalendarStyleWrapper.jsx
  Client/src/component/Header.jsx
  Client/src/component/Main.jsx
  Client/src/component/Nav.jsx
  Client/src/component/SignUpForm.jsx
  Client/src/component/diet/DeleteModal.jsx
  Client/src/component/diet/EachMeal.jsx
  Client/src/component/diet/FavoriteDailyDetail.jsx
  Client/src/component/diet/FavoriteEachItem.jsx
  Client/src/component/diet/FavoriteEachList.jsx
  Client/src/component/diet/FoodModal.jsx
  Client/src/component/diet/FoodSearchForm.jsx
  Client/src/component/diet/FoodSearchItem.jsx
  Client/src/component/diet/IsEachFood.jsx
  Client/src/component/diet/IsEachMeal.jsx
  Client/src/component/diet/NoEachMeal.jsx
  Client/src/hook/useWindowSize.jsx
  Client/src/index.css
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
  Client/src/page/Diet.jsx
  Client/src/page/Home.jsx
  Client/src/page/MyPage.jsx
  Client/src/style/style.jsx
  Client/src/util/Diet.js
  Client/src/util/FavoriteDaily.js
Labels: FE

#209 Dev fe
  Client/src/App.jsx
  Client/src/asset/hamburgerIcon.png
  Client/src/asset/navCommunityIcon.png
  Client/src/asset/navHomeIcon.png
  Client/src/asset/navMyPageIcon.png
  Client/src/asset/searchIcon.png
  Client/src/atom/GlobalModal.jsx
  Client/src/atom/Hamberger.jsx
  Client/src/atom/button.jsx
  Client/src/component/Article.jsx
  Client/src/component/Calendar.jsx
  Client/src/component/Calendar/Calendar.jsx
  Client/src/component/Calendar/CalendarStyleWrapper.jsx
  Client/src/component/Calendar/DietModal.jsx
  Client/src/component/Calendar/PostMealBtn.jsx
  Client/src/component/Comments.jsx
  Client/src/component/FavoriteDiet.jsx
  Client/src/component/Header.jsx
  Client/src/component/LoginForm.jsx
  Client/src/component/Main.jsx
  Client/src/component/Nav.jsx
  Client/src/component/PageSwitch.jsx
  Client/src/component/SearchForm.jsx
  Client/src/component/SignUpForm.jsx
  Client/src/component/diet/DeleteModal.jsx
  Client/src/component/diet/DietAnalyze.jsx
  Client/src/component/diet/DietModify.jsx
  Client/src/component/diet/EachMeal.jsx
  Client/src/component/diet/FavoriteDailyDetail.jsx
  Client/src/component/diet/FavoriteDailyItem.jsx
  Client/src/component/diet/FavoriteDailyList.jsx
  Client/src/component/diet/FavoriteEachItem.jsx
  Client/src/component/diet/FavoriteEachList.jsx
  Client/src/component/diet/FoodModal.jsx
  Client/src/component/diet/FoodSearchForm.jsx
  Client/src/component/diet/FoodSearchItem.jsx
  Client/src/component/diet/GetDailyDiet.jsx
  Client/src/component/diet/GetFood.jsx
  Client/src/component/diet/GetFoodKeyword.jsx
  Client/src/component/diet/InputAddFavorite.jsx
  Client/src/component/diet/IsEachFood.jsx
  Client/src/component/diet/IsEachMeal.jsx
  Client/src/component/diet/NoEachMeal.jsx
  Client/src/hook/useWindowSize.jsx
  Client/src/index.css
  Client/src/page/Community.jsx
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
  Client/src/page/Diet.jsx
  Client/src/page/DietAnalyzePage.jsx
  Client/src/page/EditMeal.jsx
  Client/src/page/Home.jsx
  Client/src/page/MyPage.jsx
  Client/src/style/style.jsx
  Client/src/util/Diet.js
  Client/src/util/FavoriteDaily.js
  Client/src/zustand/ArticleStore.jsx
  Client/src/zustand/Store.jsx
  README.md
Labels: FE

#211 one eachMeal save article
  Client/src/page/CommunityWrite.jsx
Labels: FE

#215 merge
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
Labels: FE

#216 Dev fe
  Client/public/image/orangeButton1.png
  Client/public/image/orangeButton2.png
  Client/public/image/orangeButton3.png
  Client/src/component/Calendar.jsx
  Client/src/component/Main.jsx
  Client/src/page/CommunityDetail.jsx
  Client/src/page/CommunityWrite.jsx
  Client/src/page/Home.jsx
Labels: FE

#236 activity range modified
  Client/src/page/MyPage.jsx
Labels: FE

#237 Dev fe
  Client/src/component/Header.jsx
  Client/src/component/diet/DeleteModal.jsx
  Client/src/index.jsx
  Client/src/page/Diet.jsx
  Client/src/page/MyPage.jsx
Labels: FE

#238 Dev
  Client/src/page/MyPage.jsx
Labels: FE
